set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm*:RGB"
set -s escape-time 0
set -g mouse on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g status-style bg=default,fg=#ebdbb2
set -g status-left-length 40
set -g status-left '[#S] '
set -g window-status-separator ' '
set -g window-status-style fg=#ebdbb2
set -g window-status-current-style fg=green
set -g window-status-format '#I:#W#F'
set -g window-status-current-format '#I:#W#F'
set -g status-right ''

bind r source-file ~/.tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

bind-key "f" run-shell "sesh connect \"$(
    find ~/projects -mindepth 2 -maxdepth 2 -type d | cat - <(echo ~/.dotfiles) | fzf-tmux -p 30%,50% \
    --no-sort --ansi
)\""

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
